#!/bin/sh

set -e
npx lint-staged
npx eslint --ignore-pattern packages/ --ignore-pattern package-lock.json .
npx lerna exec --stream --since HEAD --exclude-dependents -- "test ! -f  scripts/pre-commit.sh || bash \
scripts/pre-commit.sh"
