jobs:
  test:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Use Node.js lts
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - run: bash ./scripts/ci/dependabot-setup.sh
      - run: bash ./scripts/ci/test.sh
name: Dependabot PR check
on: pull_request_target

permissions:
  contents: write
  pull-requests: write
