env:
  CHROMATIC_PROJECT_TOKEN: ${{ secrets.REACT_COMPONENTS_CHROMATIC_PROJECT_TOKEN }}
  CI: true
jobs:
  publish-chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Use Node.js lts
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - run: bash ./scripts/ci/setup.sh
      - run: npx lerna exec --scope=@busybox/react-components bash scripts/ci/publish-storybook.sh
name: Publish to Chromatic

on:
  push:
    branches:
      - development
    paths:
      - 'packages/react-components/**'
