name: after-push-build-test

on:
  push:
    branches:
      - development
      - master

env:
  CI: true
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: bash ./scripts/setup.sh
      - run: bash ./scripts/lint.sh
      - run: bash ./scripts/test.sh
